plugin:
    name: 'logingrupa.backinstockshopaholic::lang.plugin.name'
    description: 'logingrupa.backinstockshopaholic::lang.plugin.description'
    author: Logingrupa
    icon: icon-smile-o
    homepage: ''
permissions:
    backinstockshopaholic-menu-subscribers:
        label: 'logingrupa.backinstockshopaholic::lang.permission.subscriber'
        tab: 'logingrupa.backinstockshopaholic::lang.tab.permissions'
